### ISSUE TITLE
Does this work with App Services API?

### ISSUE THREAD

**Issue by tpitman** [Unity3dAzure/AppServices#1]
It is my understanding that the Azure Mobile Services have been deprecated in favor of using the new App Services api.

Is there a library for Unity that works with App Services instead of Mobile Services?

**Comment by deadlyfingers** [comment]
Yes - With a couple of tweaks I have got this project working with Azure App Services - 
- AppKey is no longer required and needs to be removed.
- Identity auth uri needs updated to ".auth/login/<provider>" 
- Request header needs to contain "ZUMO-API-VERSION", "2.0.0"

My thoughts are - 
1. Update this current project so it will continue to work Mobile Services but merge the above changes to add support for the new Azure App API v2.0.0.
2. Or... Create a new library for App Services.
I think option 1 would be best as it means Unity devs can migrate from Mobile Services to App Services just by removing the AppKey string.

**Comment by punkouter2021** [comment]
#2

ergergergre
