### ISSUE TITLE
Post in InvokeApiAsync

### ISSUE THREAD

**Issue by JohannTIM** [Unity3dAzure/AppServices#2]
Is there any change development of post capabilities for invokeapiasync is done?

**Comment by deadlyfingers** [comment]
Currently only GET method is available. I'll try to add POST as well as PUT, PATCH and DELETE methods for Easy APIs. @JohannTIM what are you looking to POST btw - JSON or other data?

I've added this to the feature demo roadmap - 
https://github.com/Unity3dAzure/AppServicesDemo/wiki/Feature-roadmap

**Comment by deadlyfingers** [comment]
Encountering an issue using "post" method in Easy API (node backend) - its returning the "get" response in Postman app. Anyone else encountered this before? Also posted comment here -  
https://azure.microsoft.com/en-gb/documentation/articles/app-service-mobile-node-backend-how-to-use-server-sdk/

**Comment by deadlyfingers** [comment]
Ah found the answer - POST needs to be sent from "https" not "http"!

**Comment by deadlyfingers** [comment]
@JohannTIM if you want to see a Unity example I've also updated the App Services Demo. 
The _Generate Scores_ button will now submit multiple random scores with the POST method using Easy API (node backend). 

Unity InvokeApi example using POST:
https://github.com/Unity3dAzure/AppServicesDemo/blob/master/Assets/Scripts/HighscoresDemo.cs#L316

Easy API node script:
https://github.com/Unity3dAzure/AppServicesDemo#easy-api-generatescores-script-apigeneratescoresjs
